# Generated by Django 2.0.7 on 2018-11-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('date', models.DateField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('date', models.DateField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(default='', max_length=200)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Deliverable')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pipeline', models.CharField(max_length=100)),
                ('research_stream', models.BooleanField(default=False)),
                ('maturity_level', models.IntegerField()),
                ('date_of_entry', models.DateField()),
                ('website', models.CharField(max_length=200)),
                ('coorporate_existance', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('tag_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDeliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('delivery_day', models.DateField()),
                ('status', models.BooleanField()),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Deliverable')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('job_title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
            ],
            bases=('vap.user',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('role', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
            bases=('vap.user',),
        ),
        migrations.AddField(
            model_name='commentanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='team_deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.TeamDeliverable'),
        ),
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(to='vap.Coach'),
        ),
    ]
