# Generated by Django 2.1.3 on 2019-02-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('release_date', models.DateField(auto_now=True)),
                ('pipeline', models.CharField(blank=True, default='', max_length=100)),
                ('template', models.FileField(blank=True, upload_to='deliverables/')),
                ('icon', models.CharField(blank=True, default='group', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='img/')),
                ('pipeline', models.CharField(max_length=100)),
                ('research_stream', models.BooleanField(default=False)),
                ('maturity_level', models.IntegerField()),
                ('date_of_entry', models.DateField(auto_now=True)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('coorporate_existance', models.BooleanField(default=False)),
                ('tag_line', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDeliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('delivery_day', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, upload_to='media/deliverables/teams')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Deliverable')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='static/img/')),
                ('is_coach', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('field', models.CharField(blank=True, max_length=100)),
            ],
            bases=('vap.user',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('field', models.CharField(blank=True, default='', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
            bases=('vap.user',),
        ),
        migrations.AddField(
            model_name='comment',
            name='teamdeliverable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vap.TeamDeliverable'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.User'),
        ),
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(to='vap.Coach'),
        ),
    ]
