# Generated by Django 2.1.3 on 2018-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
