# Generated by Django 2.1.3 on 2019-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0002_auto_20190218_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_team_member',
        ),
        migrations.AddField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
    ]
