# Generated by Django 2.1.3 on 2019-01-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0006_auto_20190101_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='vap.Deliverable'),
        ),
        migrations.AlterField(
            model_name='question',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vap.Milestone'),
        ),
    ]
