# Generated by Django 2.1.3 on 2019-02-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0006_auto_20190219_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdeliverable',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='vap.Deliverable'),
        ),
    ]
