# Generated by Django 2.1.3 on 2019-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0007_auto_20190102_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='pipeline',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
