# Generated by Django 2.1.3 on 2019-02-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0007_auto_20190219_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
