# Generated by Django 2.1.3 on 2019-02-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0008_remove_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='coach',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vap.Coach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
