# Generated by Django 2.1.3 on 2019-01-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0010_auto_20190103_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coorporate_existance',
        ),
        migrations.RemoveField(
            model_name='team',
            name='research_stream',
        ),
    ]
