# Generated by Django 2.1.3 on 2019-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0012_remove_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdeliverable',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamdeliverable',
            name='delivery_day',
            field=models.DateField(blank=True),
        ),
    ]
