# Generated by Django 2.1.3 on 2019-01-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0013_auto_20190103_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdeliverable',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamdeliverable',
            name='delivery_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
