# Generated by Django 2.1.3 on 2019-01-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0014_auto_20190103_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='team_deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vap.TeamDeliverable'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vap.Answer'),
        ),
        migrations.AlterField(
            model_name='commentanswer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_answers', to='vap.Comment'),
        ),
    ]
