# Generated by Django 2.1.3 on 2019-02-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0015_auto_20190224_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdeliverable',
            name='delivery_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
