# Generated by Django 2.1.3 on 2019-01-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0015_auto_20190104_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='team_deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vap.TeamDeliverable'),
        ),
    ]
