# Generated by Django 2.1.3 on 2019-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0016_auto_20190104_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_of_entry',
            field=models.DateField(auto_now=True),
        ),
    ]
