# Generated by Django 2.1.3 on 2019-01-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0017_auto_20190111_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
