# Generated by Django 2.1.3 on 2019-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0018_auto_20190225_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
