# Generated by Django 2.1.3 on 2019-02-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0019_auto_20190124_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentanswer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentAnswer',
        ),
    ]
