# Generated by Django 2.1.3 on 2019-02-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0019_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
