# Generated by Django 2.1.3 on 2019-02-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0020_auto_20190225_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
