# Generated by Django 2.1.3 on 2019-02-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0020_auto_20190211_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/img/'),
        ),
    ]
