# Generated by Django 2.1.3 on 2019-02-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0021_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='team_deliverable',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='question',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AddField(
            model_name='comment',
            name='teamdeliverable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vap.TeamDeliverable'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='template',
            field=models.FileField(blank=True, upload_to='media/deliverables/'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
