# Generated by Django 2.1.3 on 2019-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0022_auto_20190213_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdeliverable',
            name='file',
            field=models.FileField(blank=True, upload_to='media/deliverables/teams'),
        ),
    ]
