# Generated by Django 2.1.3 on 2019-02-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0026_deliverable_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coorporate_existance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='research_stream',
            field=models.BooleanField(default=False),
        ),
    ]
