# Generated by Django 2.1.3 on 2019-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0027_auto_20190215_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
